library(ggplot2)
library(plyr)
hbx <- read.csv('/home/cristig/Desktop/Homeodomains/hbxRecount.csv', header=FALSE)
colnames(hbx)=c("species","groups","class", "family", "value")
hbx$species <- factor(hbx$species, c('Leucosolenia complicata','Sycon ciliatum','Amphimedon queenslandica','Oscarella carmela','Aiptasia pallida','Nematostella vectensis','Acropora digitifera','Hydra magnipapillata','Thelohanellus kitauei','Mnemiopsis leidyi','Trichoplax adhaerens','Patiria miniata','Strongylocentrotus purpuratus','Lytechinus variegatus','Ptychodera flava','Saccoglossus kowalevskii','Branchiostoma floridae','Branchiostoma belcheri','Oikopleura dioica','Ciona intestinalis','Botryllus schlosseri','Danio rerio','Homo sapiens','Anolis carolinensis','Gallus gallus','Xenopus tropicalis','Trichinella spiralis','Brugia malayi','Romanomermis culicivorax','Stegodyphus mimosarum','Ixodes scapularis','Limulus polyphemus','Daphnia pulex','Parhyale hawaiensis','Tribolium castaneum','Drosophila melanogaster','Zootermopsis nevadensis','Strigamia maritima','Hypsibius dujardini','Ramazzottius varieornatus','Helobdella robusta','Capitella teleta','Lingula anatina','Crassostrea gigas','Pinctada fucata','Octopus bimaculoides','Lottia gigantea','Intoshia linei','Hymenolepis microstoma','Echinococcus multilocularis','Gyrodactylus salaris','Schmidtea mediterranea','Macrostomum lignano','Schistosoma japonicum','Adineta vaga'))
hbx$grouping <- factor(hbx$groups, levels = c('Calcarea','Demospongiae','Homoscleromorpha','Anthozoa','Hydrozoa','Myxozoa','Tentaculata','Trichoplacidae','Ambulacraria','Chordata','Ecdysozoa','Lophotrochozoa'))
hbxplot <- ggplot(hbx, aes(x=species, y=family, fill=class, group=grouping))
hbxplot <- hbxplot + geom_tile(aes(fill=value, group=grouping), color="grey", size=0.1) + scale_fill_gradient(low ="white", high ="black", space = "Lab", na.value = "grey50", guide = "colourbar")
hbxplot <- hbxplot + theme_minimal()
hbxplot <- hbxplot + theme(axis.text.x = element_text(angle=90, size=10))
#hbxplot <- hbxplot + facet_grid(class~grouping, scales="free", space="free", switch="both")
hbxplot <- hbxplot + facet_grid(class~grouping, scales="free", space="free")
hbxplot <- hbxplot + theme(strip.text.y = element_text(size=10, angle=0))
hbxplot <- hbxplot + theme(strip.text.x = element_text(size=10, angle=90))
hbxplot <- hbxplot + theme(legend.position="none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
hbxplot <- hbxplot + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
hbxplot <- hbxplot + theme(strip.background = element_rect(color="white", fill="thistle"))

hbxplot <- hbxplot + theme(plot.margin = margin(20, 20, 20, 20))
hbxplot
ggsave("/home/cristig/Desktop/Homeodomains/hbxPlot2.pdf",  width = 12, height = 26)

